# Generated by Django 5.2.5 on 2025-08-21 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aigames', '0027_remove_obsolete_instruction_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDetectorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(default=1)),
                ('step1_completed', models.BooleanField(default=False)),
                ('step2_completed', models.BooleanField(default=False)),
                ('step3_completed', models.BooleanField(default=False)),
                ('step4_completed', models.BooleanField(default=False)),
                ('setup_data', models.JSONField(blank=True, default=dict)),
                ('collection_data', models.JSONField(blank=True, default=dict)),
                ('analysis_data', models.JSONField(blank=True, default=dict)),
                ('results_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detector_data', to='aigames.gamematchup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aigames.team')),
            ],
            options={
                'verbose_name': 'Team Detector Data',
                'verbose_name_plural': 'Team Detector Data',
                'unique_together': {('matchup', 'team')},
            },
        ),
        migrations.CreateModel(
            name='DetectorSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('submission_type', models.CharField(max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('is_validated', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='detector.teamdetectordata')),
            ],
            options={
                'verbose_name': 'Detector Submission',
                'verbose_name_plural': 'Detector Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
