# Generated by Django 5.2.1 on 2025-07-31 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigame',
            name='has_multiple_steps',
            field=models.BooleanField(default=False, help_text='Whether this game has multiple sequential steps'),
        ),
        migrations.AddField(
            model_name='aigame',
            name='student_instructions',
            field=models.TextField(blank=True, help_text='Instructions visible to students'),
        ),
        migrations.AddField(
            model_name='aigame',
            name='teacher_instructions',
            field=models.TextField(blank=True, help_text='Instructions visible to teachers (can include additional context)'),
        ),
        migrations.CreateModel(
            name='GameStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Sequential step number (1, 2, 3...)')),
                ('title', models.CharField(help_text='Title of this step', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description of what happens in this step')),
                ('student_instructions', models.TextField(help_text='Detailed instructions for students for this step')),
                ('teacher_instructions', models.TextField(blank=True, help_text='Additional instructions/context for teachers for this step')),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated time to complete this step', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='aigames.aigame')),
            ],
            options={
                'ordering': ['ai_game', 'step_number'],
                'unique_together': {('ai_game', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='TeamStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text="Optional notes about team's progress on this step")),
                ('game_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_progress', to='aigames.gamestep')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='aigames.team')),
            ],
            options={
                'ordering': ['team', 'game_step__ai_game', 'game_step__step_number'],
                'unique_together': {('team', 'game_step')},
            },
        ),
    ]
