# Generated by Django 5.2.1 on 2025-07-31 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0005_aigame_has_multiple_steps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(help_text='Short name or abbreviation', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, help_text='School logo for white-labeling', null=True, upload_to='school_logos/')),
                ('website_url', models.URLField(blank=True, help_text='School website URL')),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='aigames.school'),
        ),
    ]
