# Generated by Django 5.2.1 on 2025-07-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0008_add_school_based_teams_and_matchups'),
    ]

    operations = [
        # Remove letter density models and their related data
        migrations.DeleteModel(name='AIAgentPrediction'),
        migrations.DeleteModel(name='LetterDensityGuess'),
        migrations.DeleteModel(name='LetterDensityText'),
        migrations.DeleteModel(name='LetterDensityGame'),
    ]
