# Generated by Django 5.2.1 on 2025-07-31 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0009_remove_letter_density'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Sequential step number (1, 2, 3...)')),
                ('title', models.CharField(help_text='Title of this instruction step', max_length=255)),
                ('content', models.TextField(help_text='The instruction content for this step')),
                ('audience', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('both', 'Both Student and Teacher')], default='both', help_text='Who should see this instruction step', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this step is currently visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_steps', to='aigames.aigame')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_instruction_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ai_game', 'step_number'],
                'unique_together': {('ai_game', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='InstructionStepFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(help_text='True for thumbs up, False for thumbs down')),
                ('feedback_comment', models.TextField(blank=True, help_text='Optional comment explaining the feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instruction_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='aigames.instructionstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('instruction_step', 'user')},
            },
        ),
    ]
