# Generated by Django 5.2.1 on 2025-08-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0010_instructionstep_instructionstepfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionstep',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='instructionstep',
            name='content',
        ),
        migrations.AddField(
            model_name='instructionstep',
            name='student_content',
            field=models.TextField(default='Do some instruction', help_text='Instruction content specifically for students'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructionstep',
            name='teacher_content',
            field=models.TextField(blank=True, help_text='Instruction content specifically for teachers'),
        ),
    ]
