# Generated by Django 4.2.3 on 2025-08-02 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aigames', '0011_remove_instructionstep_audience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionstep',
            name='student_content',
        ),
        migrations.RemoveField(
            model_name='instructionstep',
            name='teacher_content',
        ),
        migrations.AddField(
            model_name='instructionstep',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of what this step covers'),
        ),
        migrations.AlterField(
            model_name='instructionstepfeedback',
            name='instruction_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_feedback', to='aigames.instructionstep'),
        ),
        migrations.AlterField(
            model_name='instructionstepfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_instruction_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TeacherInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of this instruction', max_length=255)),
                ('content', models.TextField(help_text='The instruction content for teachers')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('next_teacher_instruction', models.ForeignKey(blank=True, help_text='Next instruction in the sequence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from_teacher_instruction', to='aigames.teacherinstruction')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_instructions', to='aigames.instructionstep')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of this instruction', max_length=255)),
                ('content', models.TextField(help_text='The instruction content for students')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('next_student_instruction', models.ForeignKey(blank=True, help_text='Next instruction in the sequence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from_student_instruction', to='aigames.studentinstruction')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_instructions', to='aigames.instructionstep')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherInstructionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(help_text='True for thumbs up, False for thumbs down')),
                ('feedback_comment', models.TextField(blank=True, help_text='Optional comment explaining the feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='aigames.teacherinstruction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_instruction_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('teacher_instruction', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StudentInstructionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(help_text='True for thumbs up, False for thumbs down')),
                ('feedback_comment', models.TextField(blank=True, help_text='Optional comment explaining the feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='aigames.studentinstruction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_instruction_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student_instruction', 'user')},
            },
        ),
    ]
