# Generated by Django 4.2.3 on 2025-08-02 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aigames', '0012_remove_instructionstep_student_content_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentinstructionfeedback',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentinstructionfeedback',
            name='student_instruction',
        ),
        migrations.RemoveField(
            model_name='studentinstructionfeedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacherinstruction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='teacherinstruction',
            name='next_teacher_instruction',
        ),
        migrations.RemoveField(
            model_name='teacherinstruction',
            name='step',
        ),
        migrations.AlterUniqueTogether(
            name='teacherinstructionfeedback',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teacherinstructionfeedback',
            name='teacher_instruction',
        ),
        migrations.RemoveField(
            model_name='teacherinstructionfeedback',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='instructionstep',
            options={'ordering': ['ai_game', 'step_number', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='instructionstep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='instructionstep',
            name='content',
            field=models.TextField(blank=True, help_text='The instruction content'),
        ),
        migrations.AddField(
            model_name='instructionstep',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated time to complete this instruction', null=True),
        ),
        migrations.AddField(
            model_name='instructionstep',
            name='next_instruction',
            field=models.ForeignKey(blank=True, help_text='Next instruction in the sequence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_instruction', to='aigames.instructionstep'),
        ),
        migrations.AddField(
            model_name='instructionstep',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('both', 'Both Roles')], default='both', help_text='Which role(s) should see this instruction', max_length=10),
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this instruction is currently visible'),
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='step_number',
            field=models.PositiveIntegerField(help_text='Which step in the game (1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='title',
            field=models.CharField(help_text='Title of this instruction', max_length=255),
        ),
        migrations.AlterField(
            model_name='instructionstepfeedback',
            name='instruction_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='aigames.instructionstep'),
        ),
        migrations.AlterField(
            model_name='instructionstepfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='StudentInstruction',
        ),
        migrations.DeleteModel(
            name='StudentInstructionFeedback',
        ),
        migrations.DeleteModel(
            name='TeacherInstruction',
        ),
        migrations.DeleteModel(
            name='TeacherInstructionFeedback',
        ),
    ]
