# Generated by Django 4.2.3 on 2025-08-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0014_migrate_gamestep_to_instruction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamstepprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teamstepprogress',
            name='instruction_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_progress', to='aigames.instructionstep'),
        ),
        migrations.AlterField(
            model_name='teamstepprogress',
            name='game_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_progress', to='aigames.gamestep'),
        ),
        migrations.AlterUniqueTogether(
            name='teamstepprogress',
            unique_together={('team', 'instruction_step')},
        ),
    ]
