# Generated by Django 4.2.3 on 2025-08-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0015_update_teamstepprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstepprogress',
            name='game_step',
        ),
        migrations.DeleteModel(
            name='GameStep',
        ),
    ]
