# Generated by Django 4.2.3 on 2025-08-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0016_remove_gamestep_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructionstep',
            options={'ordering': ['game_step', 'role', 'id']},
        ),
        migrations.RemoveField(
            model_name='instructionstep',
            name='description',
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='ai_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_instruction_steps', to='aigames.aigame'),
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='content',
            field=models.TextField(help_text='The instruction content'),
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], help_text='Which role this instruction is for (student or teacher)', max_length=10),
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='step_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamstepprogress',
            name='instruction_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_team_progress', to='aigames.instructionstep'),
        ),
        migrations.CreateModel(
            name='GameStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='Sequential step number (1, 2, 3...)')),
                ('title', models.CharField(help_text='Title of this step', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description of what happens in this step')),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated time to complete this step', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='aigames.aigame')),
            ],
            options={
                'ordering': ['ai_game', 'step_number'],
                'unique_together': {('ai_game', 'step_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='teamstepprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='instructionstep',
            name='game_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instruction_steps', to='aigames.gamestep'),
        ),
        migrations.AddField(
            model_name='teamstepprogress',
            name='game_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_progress', to='aigames.gamestep'),
        ),
        migrations.AlterUniqueTogether(
            name='teamstepprogress',
            unique_together={('team', 'game_step')},
        ),
    ]
