# Generated by Django 4.2.3 on 2025-08-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0018_migrate_to_gamestep_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionstep',
            name='ai_game',
        ),
        migrations.RemoveField(
            model_name='instructionstep',
            name='step_number',
        ),
        migrations.RemoveField(
            model_name='teamstepprogress',
            name='instruction_step',
        ),
        migrations.AlterField(
            model_name='instructionstep',
            name='game_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_steps', to='aigames.gamestep'),
        ),
        migrations.AlterField(
            model_name='teamstepprogress',
            name='game_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_progress', to='aigames.gamestep'),
        ),
    ]
