# Generated by Django 4.2.3 on 2025-08-02 14:14

from django.db import migrations

def split_instructions_by_role(apps, schema_editor):
    """
    Convert all 'both' role instructions into separate 'student' and 'teacher' instructions
    """
    InstructionStep = apps.get_model('aigames', 'InstructionStep')
    
    instructions_with_both = InstructionStep.objects.filter(role='both')
    print(f"Found {instructions_with_both.count()} instructions with role 'both'")
    
    for instruction in instructions_with_both:
        # Create student version
        student_instruction = InstructionStep.objects.create(
            game_step=instruction.game_step,
            title=instruction.title,
            content=instruction.content,
            role='student',
            next_instruction=None,  # Will be set up separately if needed
            estimated_duration_minutes=instruction.estimated_duration_minutes,
            is_active=instruction.is_active,
            created_by=instruction.created_by,
        )
        
        # Create teacher version  
        teacher_instruction = InstructionStep.objects.create(
            game_step=instruction.game_step,
            title=instruction.title,
            content=instruction.content,
            role='teacher',
            next_instruction=None,  # Will be set up separately if needed
            estimated_duration_minutes=instruction.estimated_duration_minutes,
            is_active=instruction.is_active,
            created_by=instruction.created_by,
        )
        
        print(f"Split '{instruction.title}' into student and teacher versions")
        
        # Delete the original 'both' instruction
        instruction.delete()

def reverse_split_instructions_by_role(apps, schema_editor):
    """
    This reverse migration is complex and not implemented
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0019_cleanup_legacy_fields'),
    ]

    operations = [
        migrations.RunPython(
            split_instructions_by_role,
            reverse_split_instructions_by_role
        ),
    ]
