# Generated by Django 4.2.3 on 2025-08-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0020_split_instructions_by_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructionstep',
            name='estimated_duration_minutes',
        ),
        migrations.AlterField(
            model_name='gamestep',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=1, help_text='Estimated time to complete this step in minutes'),
        ),
    ]
