# Generated by Django 4.2.3 on 2025-08-02 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0021_remove_instructionstep_estimated_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigame',
            name='has_multiple_steps',
        ),
    ]
