# Generated by Django 4.2.3 on 2025-08-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0022_remove_aigame_has_multiple_steps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigame',
            name='html_page_link',
        ),
        migrations.AddField(
            model_name='gamestep',
            name='html_page_link',
            field=models.CharField(default='/placeholder-step/', help_text='Link or path to the HTML page for this game step', max_length=500),
            preserve_default=False,
        ),
    ]
