# Generated by Django 4.2.3 on 2025-08-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0023_remove_aigame_html_page_link_gamestep_html_page_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestep',
            name='html_page_link',
        ),
        migrations.AddField(
            model_name='gamestep',
            name='url_pattern',
            field=models.CharField(default='placeholder:step', help_text="URL pattern for this step (e.g., 'phoneme_density:step1_analysis')", max_length=500),
        ),
        migrations.CreateModel(
            name='MatchupStepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about progress on this step for this matchup')),
                ('game_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchup_progress', to='aigames.gamestep')),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='aigames.gamematchup')),
            ],
            options={
                'ordering': ['matchup', 'game_step__step_number'],
                'unique_together': {('matchup', 'game_step')},
            },
        ),
    ]
