# Generated by Django 4.2.3 on 2025-08-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0024_add_matchup_step_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='navbar_color',
            field=models.CharField(blank=True, help_text='Navbar color in hex format (e.g., #2E2B86)', max_length=7),
        ),
    ]
