# Generated by Django 4.2.3 on 2025-08-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0025_school_navbar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='primary_button_color',
            field=models.CharField(blank=True, help_text='Primary button color in hex format (e.g., #2E2B86)', max_length=7),
        ),
    ]
