# Generated by Django 4.2.3 on 2025-08-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0026_school_primary_button_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigame',
            name='student_instructions',
        ),
        migrations.RemoveField(
            model_name='aigame',
            name='teacher_instructions',
        ),
        migrations.DeleteModel(
            name='TeamStepProgress',
        ),
    ]
