# Generated by Django 5.2.5 on 2025-08-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0027_remove_obsolete_instruction_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamematchup',
            unique_together=set(),
        ),
    ]
