# Generated by Django 4.2.3 on 2025-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0028_remove_matchup_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestep',
            name='requires_validation',
            field=models.BooleanField(default=False, help_text='Whether this step requires teacher validation before students can proceed'),
        ),
    ]
