# Generated by Django 4.2.3 on 2025-08-24 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aigames', '0029_gamestep_requires_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStepValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_validations', to='aigames.gamematchup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aigames.team')),
                ('validated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['matchup', 'step_number', 'team'],
                'unique_together': {('matchup', 'team', 'step_number')},
            },
        ),
    ]
