# Generated by Django 4.2.3 on 2025-08-25 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aigames', '0030_teamstepvalidation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamstepvalidation',
            options={'ordering': ['matchup', 'game_step__step_number', 'team__name']},
        ),
        migrations.AlterUniqueTogether(
            name='teamstepvalidation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teamstepvalidation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamstepvalidation',
            name='game_step',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_validations', to='aigames.gamestep'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamstepvalidation',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamstepvalidation',
            name='notes',
            field=models.TextField(blank=True, help_text="Teacher notes about this team's work"),
        ),
        migrations.AlterField(
            model_name='teamstepvalidation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_validations', to='aigames.team'),
        ),
        migrations.AlterField(
            model_name='teamstepvalidation',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamstepvalidation',
            name='validated_by',
            field=models.ForeignKey(blank=True, help_text="Teacher who validated this team's work", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teamstepvalidation',
            unique_together={('matchup', 'team', 'game_step')},
        ),
        migrations.RemoveField(
            model_name='teamstepvalidation',
            name='step_number',
        ),
    ]
