# Generated by Django 5.2.1 on 2025-07-29 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aigames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('topics', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllabus.course')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='syllabus.syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='Subunit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ai_game', models.ForeignKey(blank=True, help_text='Optional AI game associated with this subunit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aigames.aigame')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subunits', to='syllabus.unit')),
            ],
        ),
    ]
