# Generated by Django 5.2.1 on 2025-07-29 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Curriculum',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='course',
            new_name='curriculum',
        ),
    ]
