# Generated by Django 5.2.1 on 2025-07-29 01:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_rename_course_curriculum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='code',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='credits',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculum',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
