# Generated by Django 5.2.1 on 2025-07-29 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_provider_remove_curriculum_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='syllabus.provider'),
            preserve_default=False,
        ),
    ]
