# Generated by Django 5.2.1 on 2025-07-29 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_curriculum_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='end_date',
            field=models.DateField(blank=True, help_text='When this curriculum expires (leave blank if still current)', null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 9, 1), help_text='When this curriculum becomes effective'),
            preserve_default=False,
        ),
    ]
