# Generated by Django 5.2.1 on 2025-07-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_curriculum_end_date_curriculum_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='year',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='name',
            field=models.CharField(default='Default Syllabus', max_length=255),
            preserve_default=False,
        ),
    ]
