# Generated by Django 5.2.1 on 2025-07-29 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0001_initial'),
        ('syllabus', '0006_remove_syllabus_semester_remove_syllabus_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='ai_game',
            field=models.ForeignKey(blank=True, help_text='Optional AI game associated with this unit', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aigames.aigame'),
        ),
        migrations.DeleteModel(
            name='Subunit',
        ),
    ]
