# Generated by Django 4.2.3 on 2025-08-23 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aigames', '0028_remove_matchup_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamOverlapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(default=1)),
                ('step1_completed', models.BooleanField(default=False)),
                ('step2_completed', models.BooleanField(default=False)),
                ('step3_completed', models.BooleanField(default=False)),
                ('step4_completed', models.BooleanField(default=False)),
                ('sensitivity_level', models.IntegerField(default=50, help_text='Sensitivity level 1-100')),
                ('threshold_value', models.FloatField(default=0.75, help_text='Detection threshold 0-1')),
                ('overlap_mode', models.CharField(default='standard', help_text='Overlap detection mode', max_length=50)),
                ('data_points_collected', models.IntegerField(default=0)),
                ('baseline_established', models.BooleanField(default=False)),
                ('collection_notes', models.TextField(blank=True)),
                ('overlap_percentage', models.FloatField(blank=True, null=True)),
                ('analysis_complete', models.BooleanField(default=False)),
                ('analysis_notes', models.TextField(blank=True)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('conclusions', models.TextField(blank=True)),
                ('game_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aigames.gamematchup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aigames.team')),
            ],
            options={
                'unique_together': {('team', 'matchup')},
            },
        ),
        migrations.CreateModel(
            name='OverlapSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('submission_data', models.JSONField(default=dict, help_text='Step-specific submission data')),
                ('notes', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(default=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('team_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overlap.teamoverlapdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team_data', 'step_number', 'user')},
            },
        ),
    ]
