# Generated by Django 4.2.3 on 2025-08-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamoverlapdata',
            name='circle_placement_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamoverlapdata',
            name='circle_x',
            field=models.FloatField(blank=True, help_text='X position of placed circle', null=True),
        ),
        migrations.AddField(
            model_name='teamoverlapdata',
            name='circle_y',
            field=models.FloatField(blank=True, help_text='Y position of placed circle', null=True),
        ),
        migrations.AddField(
            model_name='teamoverlapdata',
            name='placement_notes',
            field=models.TextField(blank=True, help_text='Notes about circle placement strategy'),
        ),
    ]
