# Generated by Django 4.2.3 on 2025-08-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlap', '0002_teamoverlapdata_circle_placement_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamoverlapdata',
            name='step4_points',
            field=models.JSONField(default=list, help_text='Points placed for gradient analysis'),
        ),
        migrations.AddField(
            model_name='teamoverlapdata',
            name='step4_total_score',
            field=models.FloatField(blank=True, help_text='Total overlap score from all points', null=True),
        ),
    ]
