# Generated by Django 4.2.3 on 2025-08-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlap', '0003_teamoverlapdata_step4_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamoverlapdata',
            name='step4_points',
        ),
        migrations.RemoveField(
            model_name='teamoverlapdata',
            name='step4_total_score',
        ),
        migrations.AddField(
            model_name='teamoverlapdata',
            name='evaluation_strategy',
            field=models.TextField(blank=True, help_text="Team's strategy for evaluating opponent's circle"),
        ),
    ]
