# Generated by Django 4.2.3 on 2025-08-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlap', '0004_remove_teamoverlapdata_step4_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamoverlapdata',
            name='click_count',
            field=models.IntegerField(default=0, help_text='Number of clicks made'),
        ),
        migrations.AddField(
            model_name='teamoverlapdata',
            name='evaluation_clicks',
            field=models.JSONField(blank=True, default=list, help_text='Stored click data as JSON'),
        ),
    ]
