# Generated by Django 5.2.5 on 2025-08-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overlap', '0006_rename_evaluation_submitted_to_step4_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamoverlapdata',
            name='reflection_notes',
            field=models.TextField(blank=True, help_text="Team's final reflection on the game and strategies"),
        ),
        migrations.AddField(
            model_name='teamoverlapdata',
            name='step5_completed',
            field=models.BooleanField(default=False),
        ),
    ]
