# Generated by Django 5.2.1 on 2025-07-31 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aigames', '0008_add_school_based_teams_and_matchups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonemeGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('target_phoneme', models.CharField(help_text='The phoneme being studied (e.g., /θ/, /s/, etc.)', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('current_step', models.IntegerField(choices=[(1, 'Step 1: Text Analysis'), (2, 'Step 2: Label Reveal'), (3, 'Step 3: Rule Reveal'), (4, 'Step 4: Text Generation'), (5, 'Step 5: Classification Competition'), (6, 'Step 6: ML Analysis Results')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneme_games', to='aigames.aigame')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_phoneme_games', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneme_games', to='aigames.school')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneme_games_as_team1', to='aigames.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneme_games_as_team2', to='aigames.team')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_correct_guesses', models.IntegerField(default=0)),
                ('team2_correct_guesses', models.IntegerField(default=0)),
                ('total_guesses', models.IntegerField(default=0)),
                ('ml_correct_predictions', models.IntegerField(default=0)),
                ('ml_total_predictions', models.IntegerField(default=0)),
                ('ml_accuracy', models.FloatField(default=0.0)),
                ('average_processing_time_ms', models.FloatField(default=0.0)),
                ('heavy_texts_submitted', models.IntegerField(default=0)),
                ('light_texts_submitted', models.IntegerField(default=0)),
                ('average_phoneme_density_heavy', models.FloatField(default=0.0)),
                ('average_phoneme_density_light', models.FloatField(default=0.0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='phoneme_density.phonemegame')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('claimed_phoneme_heavy', models.BooleanField(help_text="Team's claim: is this text phoneme heavy?")),
                ('order', models.IntegerField(help_text="Order within team's submission (1-8)")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_texts', to='phoneme_density.phonemegame')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneme_submitted_texts', to='aigames.team')),
            ],
            options={
                'ordering': ['team', 'order'],
                'unique_together': {('game', 'team', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ProviderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('is_phoneme_heavy', models.BooleanField()),
                ('order', models.IntegerField(help_text='Order for display (1-8)')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this text')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_texts', to='phoneme_density.phonemegame')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('game', 'order')},
            },
        ),
        migrations.CreateModel(
            name='StepCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(choices=[(1, 'Step 1: Text Analysis'), (2, 'Step 2: Label Reveal'), (3, 'Step 3: Rule Reveal')])),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_completions', to='phoneme_density.phonemegame')),
            ],
            options={
                'unique_together': {('game', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='MLAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_phoneme_heavy', models.BooleanField()),
                ('confidence_score', models.FloatField(help_text='Confidence score from 0.0 to 1.0')),
                ('processing_time_ms', models.IntegerField(help_text='Time taken for analysis in milliseconds')),
                ('phoneme_count', models.IntegerField(default=0)),
                ('total_phonemes', models.IntegerField(default=0)),
                ('phoneme_density', models.FloatField(default=0.0, help_text='Ratio of target phonemes to total phonemes')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm_version', models.CharField(default='v1.0', max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_results', to='phoneme_density.phonemegame')),
                ('target_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_analysis', to='phoneme_density.submittedtext')),
            ],
            options={
                'unique_together': {('game', 'target_text')},
            },
        ),
        migrations.CreateModel(
            name='ClassificationGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guessed_phoneme_heavy', models.BooleanField()),
                ('guessed_at', models.DateTimeField(auto_now_add=True)),
                ('guessed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('guessing_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneme_guesses', to='aigames.team')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_guesses', to='phoneme_density.phonemegame')),
                ('target_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guesses', to='phoneme_density.submittedtext')),
            ],
            options={
                'unique_together': {('guessing_team', 'target_text')},
            },
        ),
    ]
