# Generated by Django 4.2.3 on 2025-08-05 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0027_remove_obsolete_instruction_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phoneme_density', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStep4Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_phoneme', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step4_data', to='aigames.gamematchup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aigames.team')),
            ],
            options={
                'unique_together': {('matchup', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TeamText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_number', models.IntegerField()),
                ('content', models.TextField(blank=True)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Needs Revision')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('teacher_feedback', models.TextField(blank=True)),
                ('phoneme_count', models.IntegerField(default=0)),
                ('total_characters', models.IntegerField(default=0)),
                ('phoneme_density', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('step4_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='phoneme_density.teamstep4data')),
            ],
            options={
                'ordering': ['text_number'],
                'unique_together': {('step4_data', 'text_number')},
            },
        ),
        migrations.RemoveField(
            model_name='gamestatistics',
            name='game',
        ),
        migrations.AlterUniqueTogether(
            name='mlanalysisresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mlanalysisresult',
            name='game',
        ),
        migrations.RemoveField(
            model_name='mlanalysisresult',
            name='target_text',
        ),
        migrations.RemoveField(
            model_name='phonemegame',
            name='ai_game',
        ),
        migrations.RemoveField(
            model_name='phonemegame',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='phonemegame',
            name='school',
        ),
        migrations.RemoveField(
            model_name='phonemegame',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='phonemegame',
            name='team2',
        ),
        migrations.AlterUniqueTogether(
            name='providertext',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='providertext',
            name='game',
        ),
        migrations.AlterUniqueTogether(
            name='stepcompletion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stepcompletion',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='stepcompletion',
            name='game',
        ),
        migrations.AlterUniqueTogether(
            name='submittedtext',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='submittedtext',
            name='game',
        ),
        migrations.RemoveField(
            model_name='submittedtext',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='submittedtext',
            name='team',
        ),
        migrations.DeleteModel(
            name='ClassificationGuess',
        ),
        migrations.DeleteModel(
            name='GameStatistics',
        ),
        migrations.DeleteModel(
            name='MLAnalysisResult',
        ),
        migrations.DeleteModel(
            name='PhonemeGame',
        ),
        migrations.DeleteModel(
            name='ProviderText',
        ),
        migrations.DeleteModel(
            name='StepCompletion',
        ),
        migrations.DeleteModel(
            name='SubmittedText',
        ),
    ]
