# Generated by Django 4.2.3 on 2025-08-14 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aigames', '0027_remove_obsolete_instruction_fields'),
        ('phoneme_density', '0002_teamstep4data_teamtext_remove_gamestatistics_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonemeGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneme_guess', models.CharField(blank=True, max_length=10, null=True)),
                ('rule_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guessing_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneme_guesses_made', to='aigames.team')),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneme_guesses', to='aigames.gamematchup')),
                ('target_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phoneme_guesses_received', to='aigames.team')),
            ],
            options={
                'unique_together': {('matchup', 'guessing_team', 'target_team')},
            },
        ),
        migrations.CreateModel(
            name='TextGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_number', models.IntegerField()),
                ('follows_rule', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phoneme_guess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_guesses', to='phoneme_density.phonemeguess')),
            ],
            options={
                'ordering': ['text_number'],
                'unique_together': {('phoneme_guess', 'text_number')},
            },
        ),
    ]
